const books = [
  {
    id: '1',
    title: 'Book 1',
    description: 'Description of Book 1',
    author: 'Author 1',
    publicationDate: '2022-01-01',
    genre: 'Science fiction',
    price: 9.99,
  },
  {
    id: '2',
    title: 'Book 2',
    description: 'Description of Book 2',
    author: 'Author 2',
    publicationDate: '2022-02-01',
    genre: 'Satire',
    price: 14.99,
  },
  {
    id: '3',
    title: 'Book 3',
    description: 'Description of Book 3',
    author: 'Author 3',
    publicationDate: '2022-03-01',
    genre: 'Drama',
    price: 12.99,
  },
  {
    id: '4',
    title: 'Book 4',
    description: 'Description of Book 4',
    author: 'Author 4',
    publicationDate: '2022-04-01',
    genre: 'Action',
    price: 19.99,
  },
  {
    id: '5',
    title: 'Book 5',
    description: 'Description of Book 5',
    author: 'Author 5',
    publicationDate: '2022-05-01',
    genre: 'Romance',
    price: 10.99,
  },
  {
    id: '6',
    title: 'Book 6',
    description: 'Description of Book 6',
    author: 'Author 6',
    publicationDate: '2022-06-01',
    genre: 'Mystery',
    price: 16.99,
  },
  {
    id: '7',
    title: 'Book 7',
    description: 'Description of Book 7',
    author: 'Author 7',
    publicationDate: '2022-07-01',
    genre: 'Horror',
    price: 13.99,
  },
];

module.exports = books;
